### ISSUE TITLE
Todo 6/28

### ISSUE THREAD

**Issue by very-amused** [very-amused/apfs.xyz#1]
- [x] Write page for MC server
- [x] Add login system with MariaDB

Improve mobile CSS using media queries in:

- [ ] Homepage
- [ ] Upload Page
- [ ] Login Page
- [ ] MC Server Page

**Comment by very-amused** [comment]
Closing due to a change in frontend focus. The site now uses Bootstrap 4 for styling with very little custom CSS. I eventually plan to implement dedicated mobile pages using a subdomain (`m.apfs.xyz`), but this to-do list holds no relevant information to the current development of the site anymore.
