### ISSUE TITLE
Todo 9/6/19

### ISSUE THREAD

**Issue by very-amused** [very-amused/apfs.xyz#3]
# Backend
- [x] Restructure npm package.json
I would like to set things up that the website has a `package.json` which lists the packages used in any apps in the entire website in the root directory, instead of the current solution of each node app having a separate `package.json` file. *This has the added performance and storage benefit that npm packages only need to be installed one time to be used across multiple node apps.*

- [x] Configure automatic database configuration based on `NODE_ENV` environment variable
Write code to read the environment (development or production) from the `NODE_ENV` environment variable, and configure which database is connected to accordingly

### Attempt migration to TypeScript
This may not be successful, but I would like to attempt (for the second time) to migrate the codebase of all of this website's JavaScript code to TypeScript for better stability, scalability, and code cleanliness. This migration can be broken down into the following substeps:
- [x] Configure Babel for compiling TS with a build script for production
- [x] Configure [ts-node-dev](https://github.com/whitecolor/ts-node-dev) for running TypeScript in a development environment
- [x] Rewrite JS code as TS code, placing everything inside of a `src` directory
- [x] Reconfigure eslint to work with TS files using [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint)

**Comment by very-amused** [comment]
Update: the migration to TypeScript was a massive success! The entire codebase was moved in commit https://github.com/very-amused/apfs.xyz/commit/4e5a8decd1c10564e4894f2458102b0bd0fd65f3. Babel was not used in the end for compiling, because it doesn't actually have compile time type checking, just removal of type definitions.
