### ISSUE TITLE
Todo 9/7/19

### ISSUE THREAD

**Issue by very-amused** [very-amused/apfs.xyz#4]
# Frontend
- [x] Move all static assets (CSS, frontend JS, images) to static hosting with express.static in the [static](https://github.com/very-amused/apfs.xyz/tree/development/static) folder.
- [ ] Rewrite HTML pages as pug templates for readability and code cleanliness
- [ ] Continue migration of CSS to Bootstrap 4

**Comment by very-amused** [comment]
Closing because I've made a decision to migrate the CSS to [Google's Materialize](https://materializecss.com/) instead of Bootstrap 4.
