### ISSUE TITLE
Todo 9/8/19

### ISSUE THREAD

**Issue by very-amused** [very-amused/apfs.xyz#5]
# Frontend
- [ ] Rewrite pug templates/html pages (again) in [Materialize](https://materializecss.com/)
I've decided that Materialize is going to be a better fit for the look I want this site to have compared to Bootstrap 4. An added benefit is that it doesn't depend on JQuery, an old, outdated library that I would prefer not to ship with every rendered page.
- [ ] Move all html to SSR with pug templates

# Backend
- [ ] Find some way to backup Nginx config files???
*(This might not happen)*
